version: 2
updates:
  - package-ecosystem: "npm" # Specify the package ecosystem
    directory: "/" # Specify the directory where the package is located
    schedule:
      interval: "weekly" # Specify the update interval
    commitMessage:
      prefix: "chore(deps):" # Specify the commit message prefix
      include: "updated dependencies" # Specify the commit message content
      
